=== Vexilla/vexilla/packages/types/schema/v1/group.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://vexilla.dev/schema/v1/group.json",
  "title": "PublishedGroup",
  "type": "object",
  "required": [
    "name",
    "groupId",
    "meta",
    "features",
    "environments"
  ],
  "properties": {
    "name": {
      "type": "string"
    },
    "groupId": {
      "type": "string",
      "minLength": 1
    },
    "meta": {
      "type": "object",
      "required": [
        "version"
      ],
      "properties": {
        "version": {
          "const": "v1"
        }
      },
      "additionalProperties": true
    },
    "features": {
      "type": "object",
      "additionalProperties": {
        "$ref": "feature.json"
      }
    },
    "environments": {
      "type": "object",
      "additionalProperties": {
        "title": "PublishedEnvironment",
        "type": "object",
        "required": [
          "name",
          "environmentId",
          "features"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "environmentId": {
            "type": "string",
            "minLength": 1
          },
          "features": {
            "type": "object",
            "additionalProperties": {
              "$ref": "feature.json"
            }
          }
        },
        "additionalProperties": true
      }
    }
  },
  "additionalProperties": true
}

=== Vexilla/vexilla/clients/ocaml/lib/example.json
{
  "name": "Scheduled",
  "groupId": "Jz0rgEv0epyCb6z58or72",
  "features": {
    "7tmnvFX7RI3kOt5r57vyz": {
      "name": "beforeGlobal",
      "featureId": "7tmnvFX7RI3kOt5r57vyz",
      "featureType": "toggle",
      "value": false,
      "scheduleType": "global",
      "schedule": {
        "start": 0,
        "end": 0,
        "timezone": "UTC",
        "timeType": "none",
        "startTime": 0,
        "endTime": 0
      }
    },
    "khEhXchcRuhNdDa8Il8VO": {
      "name": "duringGlobal",
      "featureId": "khEhXchcRuhNdDa8Il8VO",
      "featureType": "toggle",
      "value": false,
      "scheduleType": "global",
      "schedule": {
        "start": 0,
        "end": 0,
        "timezone": "UTC",
        "timeType": "none",
        "startTime": 0,
        "endTime": 0
      }
    },
    "dPjTTjugWI5gJfcmoDmbU": {
      "name": "afterGlobal",
      "featureId": "dPjTTjugWI5gJfcmoDmbU",
      "featureType": "toggle",
      "value": false,
      "scheduleType": "global",
      "schedule": {
        "start": 0,
        "end": 0,
        "timezone": "UTC",
        "timeType": "none",
        "startTime": 0,
        "endTime": 0
      }
    },
    "6iaSljA2uE74IPq4gNzEv": {
      "name": "beforeGlobalStartEnd",
      "featureId": "6iaSljA2uE74IPq4gNzEv",
      "featureType": "toggle",
      "value": false,
      "scheduleType": "global",
      "schedule": {
        "start": 0,
        "end": 0,
        "timezone": "UTC",
        "timeType": "none",
        "startTime": 0,
        "endTime": 0
      }
    },
    "0cq1IesUoQ7co34ViqHY8": {
      "name": "duringGlobalStartEnd",
      "featureId": "0cq1IesUoQ7co34ViqHY8",
      "featureType": "toggle",
      "value": false,
      "scheduleType": "global",
      "schedule": {
        "start": 0,
        "end": 0,
        "timezone": "UTC",
        "timeType": "none",
        "startTime": 0,
        "endTime": 0
      }
    },
    "PKjpuHwBkjmofQlj-o3q5": {
      "name": "afterGlobalStartEnd",
      "featureId": "PKjpuHwBkjmofQlj-o3q5",
      "featureType": "toggle",
      "value": false,
      "scheduleType": "global",
      "schedule": {
        "start": 0,
        "end": 0,
        "timezone": "UTC",
        "timeType": "none",
        "startTime": 0,
        "endTime": 0
      }
    },
    "hErE-2S6DeJBybg-zjo-h": {
      "name": "beforeGlobalDaily",
      "featureId": "hErE-2S6DeJBybg-zjo-h",
      "featureType": "toggle",
      "value": false,
      "scheduleType": "global",
      "schedule": {
        "start": 0,
        "end": 0,
        "timezone": "UTC",
        "timeType": "none",
        "startTime": 0,
        "endTime": 0
      }
    },
    "VOg2MtzQbaAvZJLSyYXo_": {
      "name": "duringGlobalDaily",
      "featureId": "VOg2MtzQbaAvZJLSyYXo_",
      "featureType": "toggle",
      "value": false,
      "scheduleType": "global",
      "schedule": {
        "start": 0,
        "end": 0,
        "timezone": "UTC",
        "timeType": "none",
        "startTime": 0,
        "endTime": 0
      }
    },
    "dA_c61EnCwPL0ENcAbzJF": {
      "name": "afterGlobalDaily",
      "featureId": "dA_c61EnCwPL0ENcAbzJF",
      "featureType": "toggle",
      "value": false,
      "scheduleType": "global",
      "schedule": {
        "start": 0,
        "end": 0,
        "timezone": "UTC",
        "timeType": "none",
        "startTime": 0,
        "endTime": 0
      }
    }
  },
  "environments": {
    "HRHIqkJIGYuPbZpvF74mi": {
      "name": "dev",
      "environmentId": "HRHIqkJIGYuPbZpvF74mi",
      "features": {
        "7tmnvFX7RI3kOt5r57vyz": {
          "name": "beforeGlobal",
          "featureId": "7tmnvFX7RI3kOt5r57vyz",
          "featureType": "toggle",
          "value": true,
          "scheduleType": "global",
          "schedule": {
            "start": 1691132400000,
            "end": 1691737200000,
            "timezone": "UTC",
            "timeType": "none",
            "startTime": 0,
            "endTime": 0
          }
        },
        "khEhXchcRuhNdDa8Il8VO": {
          "name": "duringGlobal",
          "featureId": "khEhXchcRuhNdDa8Il8VO",
          "featureType": "toggle",
          "value": true,
          "scheduleType": "global",
          "schedule": {
            "start": 1690527600000,
            "end": 1691132400000,
            "timezone": "UTC",
            "timeType": "none",
            "startTime": 0,
            "endTime": 0
          }
        },
        "dPjTTjugWI5gJfcmoDmbU": {
          "name": "afterGlobal",
          "featureId": "dPjTTjugWI5gJfcmoDmbU",
          "featureType": "toggle",
          "value": true,
          "scheduleType": "global",
          "schedule": {
            "start": 1689922800000,
            "end": 1690527600000,
            "timezone": "UTC",
            "timeType": "none",
            "startTime": 0,
            "endTime": 0
          }
        },
        "6iaSljA2uE74IPq4gNzEv": {
          "name": "beforeGlobalStartEnd",
          "featureId": "6iaSljA2uE74IPq4gNzEv",
          "featureType": "toggle",
          "value": true,
          "scheduleType": "global",
          "schedule": {
            "start": 1691132400000,
            "end": 1691737200000,
            "timezone": "UTC",
            "timeType": "start/end",
            "startTime": 32400000,
            "endTime": 61200000
          }
        },
        "0cq1IesUoQ7co34ViqHY8": {
          "name": "duringGlobalStartEnd",
          "featureId": "0cq1IesUoQ7co34ViqHY8",
          "featureType": "toggle",
          "value": true,
          "scheduleType": "global",
          "schedule": {
            "start": 1690527600000,
            "end": 1691132400000,
            "timezone": "UTC",
            "timeType": "start/end",
            "startTime": 32400000,
            "endTime": 61200000
          }
        },
        "PKjpuHwBkjmofQlj-o3q5": {
          "name": "afterGlobalStartEnd",
          "featureId": "PKjpuHwBkjmofQlj-o3q5",
          "featureType": "toggle",
          "value": true,
          "scheduleType": "global",
          "schedule": {
            "start": 1689922800000,
            "end": 1690527600000,
            "timezone": "UTC",
            "timeType": "start/end",
            "startTime": 32400000,
            "endTime": 61200000
          }
        },
        "hErE-2S6DeJBybg-zjo-h": {
          "name": "beforeGlobalDaily",
          "featureId": "hErE-2S6DeJBybg-zjo-h",
          "featureType": "toggle",
          "value": true,
          "scheduleType": "global",
          "schedule": {
            "start": 1691737200000,
            "end": 1692342000000,
            "timezone": "UTC",
            "timeType": "daily",
            "startTime": 32400000,
            "endTime": 61200000
          }
        },
        "VOg2MtzQbaAvZJLSyYXo_": {
          "name": "duringGlobalDaily",
          "featureId": "VOg2MtzQbaAvZJLSyYXo_",
          "featureType": "toggle",
          "value": true,
          "scheduleType": "global",
          "schedule": {
            "start": 1690527600000,
            "end": 1691132400000,
            "timezone": "UTC",
            "timeType": "daily",
            "startTime": 32400000,
            "endTime": 43200000
          }
        },
        "dA_c61EnCwPL0ENcAbzJF": {
          "name": "afterGlobalDaily",
          "featureId": "dA_c61EnCwPL0ENcAbzJF",
          "featureType": "toggle",
          "value": true,
          "scheduleType": "global",
          "schedule": {
            "start": 1689922800000,
            "end": 1690527600000,
            "timezone": "UTC",
            "timeType": "daily",
            "startTime": 32400000,
            "endTime": 61200000
          }
        }
      }
    }
  },
  "meta": {
    "version": "v1"
  }
}

=== Vexilla/vexilla/packages/test-server/fixtures/N-MDzoxJanbPOPg223Twf.json
{
  "name": "Value",
  "groupId": "N-MDzoxJanbPOPg223Twf",
  "features": {
    "Qp0lpyynA5H032t0z07Km": {
      "name": "Integer",
      "featureId": "Qp0lpyynA5H032t0z07Km",
      "featureType": "value",
      "value": 0,
      "scheduleType": "",
      "schedule": {
        "start": 0,
        "end": 0,
        "timezone": "UTC",
        "timeType": "none",
        "startTime": 0,
        "endTime": 0
      },
      "valueType": "number",
      "numberType": "int"
    },
    "zRMmnUwKylOtX0tiQnxys": {
      "name": "Float",
      "featureId": "zRMmnUwKylOtX0tiQnxys",
      "featureType": "value",
      "value": 0,
      "scheduleType": "",
      "schedule": {
        "start": 0,
        "end": 0,
        "timezone": "UTC",
        "timeType": "none",
        "startTime": 0,
        "endTime": 0
      },
      "valueType": "number",
      "numberType": "float"
    },
    "wkXA-cD1FHbf16yIHnPVi": {
      "name": "String",
      "featureId": "wkXA-cD1FHbf16yIHnPVi",
      "featureType": "value",
      "value": "false",
      "scheduleType": "",
      "schedule": {
        "start": 0,
        "end": 0,
        "timezone": "UTC",
        "timeType": "none",
        "startTime": 0,
        "endTime": 0
      },
      "valueType": "string"
    }
  },
  "environments": {
    "2CyvAAPow7cMHvlFFvuFj": {
      "name": "dev",
      "environmentId": "2CyvAAPow7cMHvlFFvuFj",
      "features": {
        "Qp0lpyynA5H032t0z07Km": {
          "name": "Integer",
          "featureId": "Qp0lpyynA5H032t0z07Km",
          "featureType": "value",
          "valueType": "number",
          "value": 42,
          "scheduleType": "",
          "schedule": {
            "start": 0,
            "end": 0,
            "timezone": "UTC",
            "timeType": "none",
            "startTime": 0,
            "endTime": 0
          },
          "numberType": "int"
        },
        "zRMmnUwKylOtX0tiQnxys": {
          "name": "Float",
          "featureId": "zRMmnUwKylOtX0tiQnxys",
          "featureType": "value",
          "valueType": "number",
          "value": 42.42,
          "scheduleType": "",
          "schedule": {
            "start": 0,
            "end": 0,
            "timezone": "UTC",
            "timeType": "none",
            "startTime": 0,
            "endTime": 0
          },
          "numberType": "float"
        },
        "wkXA-cD1FHbf16yIHnPVi": {
          "name": "String",
          "featureId": "wkXA-cD1FHbf16yIHnPVi",
          "featureType": "value",
          "valueType": "string",
          "value": "foo",
          "scheduleType": "",
          "schedule": {
            "start": 0,
            "end": 0,
            "timezone": "UTC",
            "timeType": "none",
            "startTime": 0,
            "endTime": 0
          }
        }
      }
    }
  },
  "meta": {
    "version": "v1"
  }
}

=== Vexilla/vexilla/packages/test-server/fixtures/SqR8BqpM6qgKxVtohkZE1.json
{
  "name": "Selective",
  "groupId": "SqR8BqpM6qgKxVtohkZE1",
  "features": {
    "JWXHmkf_Sct1Jr2lqACRT": {
      "name": "String",
      "featureId": "JWXHmkf_Sct1Jr2lqACRT",
      "featureType": "selective",
      "value": [],
      "scheduleType": "",
      "schedule": {
        "start": 0,
        "end": 0,
        "timezone": "UTC",
        "timeType": "none",
        "startTime": 0,
        "endTime": 0
      },
      "valueType": "string"
    },
    "dlvHPXpmQ94KIzt3V-y4D": {
      "name": "Number",
      "featureId": "dlvHPXpmQ94KIzt3V-y4D",
      "featureType": "selective",
      "value": [],
      "scheduleType": "",
      "schedule": {
        "start": 0,
        "end": 0,
        "timezone": "UTC",
        "timeType": "none",
        "startTime": 0,
        "endTime": 0
      },
      "numberType": "int",
      "valueType": "number"
    }
  },
  "environments": {
    "mEghvHGNfmfHwoPT82We-": {
      "name": "dev",
      "environmentId": "mEghvHGNfmfHwoPT82We-",
      "features": {
        "JWXHmkf_Sct1Jr2lqACRT": {
          "name": "String",
          "featureId": "JWXHmkf_Sct1Jr2lqACRT",
          "featureType": "selective",
          "valueType": "string",
          "value": ["b7e91cc5-ec76-4ec3-9c1c-075032a13a1a", "shouldBeInList"],
          "scheduleType": "",
          "schedule": {
            "start": 0,
            "end": 0,
            "timezone": "UTC",
            "timeType": "none",
            "startTime": 0,
            "endTime": 0
          }
        },
        "dlvHPXpmQ94KIzt3V-y4D": {
          "name": "Number",
          "featureId": "dlvHPXpmQ94KIzt3V-y4D",
          "featureType": "selective",
          "valueType": "number",
          "value": [42],
          "scheduleType": "",
          "schedule": {
            "start": 0,
            "end": 0,
            "timezone": "UTC",
            "timeType": "none",
            "startTime": 0,
            "endTime": 0
          },
          "numberType": "int"
        }
      }
    }
  },
  "meta": {
    "version": "v1"
  }
}

=== Vexilla/vexilla/packages/test-server/fixtures/aKS-wxK2mMbeYxVVFSV8p.json
{
  "name": "Gradual",
  "groupId": "aKS-wxK2mMbeYxVVFSV8p",
  "features": {
    "oIVHzosp0ao3HN0fmFwwr": {
      "name": "testingWorkingGradual",
      "featureId": "oIVHzosp0ao3HN0fmFwwr",
      "featureType": "gradual",
      "value": 0,
      "seed": 0.32,
      "scheduleType": "",
      "schedule": {
        "start": 0,
        "end": 0,
        "timezone": "UTC",
        "timeType": "none",
        "startTime": 0,
        "endTime": 0
      }
    },
    "-T2se1u9jyj1HNkbJ9Cdr": {
      "name": "testingNonWorkingGradual",
      "featureId": "-T2se1u9jyj1HNkbJ9Cdr",
      "featureType": "gradual",
      "value": 0,
      "seed": 0.22,
      "scheduleType": "",
      "schedule": {
        "start": 0,
        "end": 0,
        "timezone": "UTC",
        "timeType": "none",
        "startTime": 0,
        "endTime": 0
      }
    }
  },
  "environments": {
    "zq-d4W97nyNo3mELbO_LT": {
      "name": "dev",
      "environmentId": "zq-d4W97nyNo3mELbO_LT",
      "features": {
        "oIVHzosp0ao3HN0fmFwwr": {
          "name": "testingWorkingGradual",
          "featureId": "oIVHzosp0ao3HN0fmFwwr",
          "featureType": "gradual",
          "seed": 0.32,
          "value": 0.4,
          "scheduleType": "",
          "schedule": {
            "start": 0,
            "end": 0,
            "timezone": "UTC",
            "timeType": "none",
            "startTime": 0,
            "endTime": 0
          }
        },
        "-T2se1u9jyj1HNkbJ9Cdr": {
          "name": "testingNonWorkingGradual",
          "featureId": "-T2se1u9jyj1HNkbJ9Cdr",
          "featureType": "gradual",
          "seed": 0.22,
          "value": 0.4,
          "scheduleType": "",
          "schedule": {
            "start": 0,
            "end": 0,
            "timezone": "UTC",
            "timeType": "none",
            "startTime": 0,
            "endTime": 0
          }
        }
      }
    }
  },
  "meta": {
    "version": "v1"
  }
}
